# Generated by Django 5.2.3 on 2025-06-27 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="category",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="expense",
            name="date",
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name="expense",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
